### ISSUE TITLE
generate document

### ISSUE THREAD

**Issue by ali3assi** [nateraw/Lda2vec-Tensorflow#1]
Please send me your private email. I wanna send you private code about generating topics for test document. 

Did ytou get the chance to implement it?

**Comment by nateraw** [comment]
nxr9266@rit.edu

Working on it right now!

**Comment by ali3assi** [comment]
The problem if send you something it  will appear there and i want to be private cause the code not for me but i have the permission to share with you

**Comment by nateraw** [comment]
It will be private, yes. Don't send through github, send an email directly to my email.

**Comment by nateraw** [comment]
I'm closing this issue because until we get a working example going, there is no point in trying to alter the model in this way. For now, it is out of scope.
