### ISSUE TITLE
Unable to install LDA2Vec in Windows

### ISSUE THREAD

**Issue by 21st-sam** [nateraw/Lda2vec-Tensorflow#10]
I'm trying to install LDA2Vec in VirtualEnv by downloading Lda2vec-Tensorflow.zip and install it through pip install setup.py but the procedure show the following error.

Windows 10 64bit
Python 3.6.2

![image](https://user-images.githubusercontent.com/24217714/44742153-cc4f8e80-ab1c-11e8-9424-89e1492f1b84.png)

**Comment by nateraw** [comment]
The pip install is definitely broken :persevere:. For now, I guess unpack the code yourself. It's my first time setting pip install up, so it's not perfect. Sorry about that!

**Comment by iantheparker** [comment]
I'm getting `No module named lda2vec.nlppipe` when attempting to install in Colaboratory

```
!pip install lda2vec
from lda2vec.nlppipe import NlpPipeline
```

**Comment by 21st-sam** [comment]
@nateraw is there any other way to install LDA2Vec other than pip. How did you install? Could you please let me know?
@iantheparker !pip install lda2vec wont work as the setup.py in the pypi lda2vec package doesn't have any code.

**Comment by nateraw** [comment]
The quick and dirty solution to your problem is to unpack all the files within the lda2vec folder and then import them directly. To use nlppipe you'll have to install spacy 2. Hope this helps for now!!

**Comment by 21st-sam** [comment]
@nateraw This would be an inappropriate place to ask this question. Please bear with me. I ran the lda2vec code, the topics generated are all ovelapping. All the topics show the same words in their most frequent words. Any idea on why is this happening?

**Comment by nateraw** [comment]
You have to let it train for a long time. At least 20 epochs. Also, the algorithm is finicky. Sometimes you'll find drastically different results if you preprocess your text differently.

**Comment by 21st-sam** [comment]
I have set the epochs to 500. But still the topics generated are all overlapping. If you dont mind, Shall i share the Data and the code with you. Can you take a look?

**Comment by nateraw** [comment]
Sure, email me: nxr9266@rit.edu

**Comment by 21st-sam** [comment]
i have emailed you. take a look.

**Comment by nateraw** [comment]
You should be running this as:
```python setup.py install```

Additionally, there are some dependencies you will have to install:
pyLDAvis
sense2vec==1.0.0a0

**Comment by nateraw** [comment]
Also, in the setup.py file, you can change the line:

```packages=find_packages("lda2vec")``` to ```packages=find_packages()```

I'll see if I can get these changes pushed ASAP.
