### ISSUE TITLE
about Sense2VecComponent

### ISSUE THREAD

**Issue by schneeLee** [nateraw/Lda2vec-Tensorflow#14]
hi, I download the code and installed all required packages, but there is still a problem in "from sense2vec import Sense2VecComponent"---unresolved reference "Sense2VecComponent". any idea to solving it? thanks.

**Comment by nateraw** [comment]
Please take a look at this link:

https://github.com/explosion/sense2vec

You will need to download the reddit vectors from here too. Will edit comment when I'm not on mobile to be more helpful, in case you cant figure it out from this. Hope this helps!

**Comment by schneeLee** [comment]
thanks, its very helpful!!

**Comment by schneeLee** [comment]
hi，when I user the command "pip install sense2vec==1.0.0a0" to install sense2vec, I got this error:
pip install sense2vec==1.0.0a0
Collecting sense2vec==1.0.0a0
  Using cached https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\schnee\AppData\Local\Temp\pip-install-d1zrx4n8\sense2vec\setup.py", line 169, in <module>
        setup_package()
      File "C:\Users\schnee\AppData\Local\Temp\pip-install-d1zrx4n8\sense2vec\setup.py", line 107, in setup_package
        readme = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 5415: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\schnee\AppData\Local\Temp\pip-install-d1zrx4n8\sense2vec\
any suggestions?  operating system : win10 64bit.  any help would be appreciate. 
furthermore, can you tell me which version of spacy and sense2vec you use?

**Comment by nateraw** [comment]
That's the same version I was using for Sense2Vec. I've never tried to install it on windows. Spacy is notorious for being difficult to work with on Windows. I am in NY, and my windows desktop is in CO. I'll check and see if I can get it working when I return tomorrow. Until then, maybe check their github issues? Sorry, I know how frustrating this can be. Until then, if you would like to use the preprocessing class, please change the parameter "merge" to equal False upon instantiation.

**Comment by nateraw** [comment]
Changing batch size should work well for reducing memory. I'm looking into other options for preprocessing.

Remember to train for at least 20 epochs. 

As for Chinese corpus, I have no idea how that would work. If you preprocess the data yourself, you may be able to see it work though. If you do, please show me your results :)
