### ISSUE TITLE
OOM with GPU computing

### ISSUE THREAD

**Issue by cyberyu** [nateraw/Lda2vec-Tensorflow#19]
Great package!

I tried to speed up my computation on a cloud based GPU P2 (K80 GPU) instance using an ancient Tensorflow-GPU package (1.2.1).  I think it doesn't have run option setting for report_tensor_allocations_upon_oom=True,  so I set my batch size to 10.

I found it still went OOM when trying to build a graph of (10967, 20).  I attached the screen shot here. Maybe the batch size is not actually used in some place of the code?  Just curious. 

I haven't tried this on my own GPU yet,  not sure the same error occurs on more recent TF package with the correct run option setting.  

(Updated.  I just ran the code on EC2 instance with TF-GPU 1.09, and it has no error.  I guess the issue is incompatibility with old TF package.  However, fixing that OOM may require some changes in the code. 

<img width="1069" alt="2019-02-17_1131" src="https://user-images.githubusercontent.com/7463258/52915958-1df4fc80-32a8-11e9-9cd1-9a8f1d7d9f02.png">

**Comment by nateraw** [comment]
Thanks for your feedback! I have no idea how to fix this. Do you have any insight?

**Comment by nateraw** [comment]
Closing because I don't think this is in scope. Definitely still open to suggestions on this, though. Thanks!
