### ISSUE TITLE
spacy-related error

### ISSUE THREAD

**Issue by gveni** [nateraw/Lda2vec-Tensorflow#32]
I am getting the following error after running the preprocessing code provided.
File "***/nlppipe.py", line 41, in __init__
    self.nlp = spacy.load(nlp, disable = ['ner', 'tagger', 'parser'])
  File "***/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "***/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
Any help would be appreciated

**Comment by nateraw** [comment]
I'm on mobile and walking right now so I cant link you, but you need to download the spacy model "en_core_web_lg" or any of their other models and pass whatever one you downloaded as a string to the nlp parameter. Check their site for more info

**Comment by dbl001** [comment]
https://spacy.io/models/en

**Comment by dbl001** [comment]
You have to download the Spacy model:


python -m spacy download en_core_web_lg

**Comment by gveni** [comment]
Thanks a lot for all the prompt responses. I appreciate it!
Worked!

**Comment by nateraw** [comment]
Thanks @dbl001 :smiley:
