### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'load_embeds'

### ISSUE THREAD

**Issue by gveni** [nateraw/Lda2vec-Tensorflow#33]
Now I am trying to run the actual lda2vec process, I get the following error:

freqs=freqs) # Python list of shape (vocab_size,). Frequencies of each token, same order as embed matrix mappings.
TypeError: __init__() got an unexpected keyword argument 'load_embeds'

Any help is appreciated. Thanks!

**Comment by dbl001** [comment]
I got that problem also.

**Comment by nateraw** [comment]
Whoops, thought I replied yesterday! That's what I get for being on mobile. The arguments changed in that function 2 days ago (which is one of the reasons I added a warning in the readme). `load_embeds` is no longer a parameter of the init function.

There were 2 redundant parameters previously: `load_embeds` and `pretrained_embeddings`. These have now turned into a single parameter `w_in` which is None by default. If you pass your numpy array of pretrained embeddings to the `w_in` parameter, it will do the same thing as having `load_embeds=True, pretrained_embeddings=embedding_matrix`.

**Comment by nateraw** [comment]
Also, I'm open to changing the `w_in` parameter name to `pretrained_embeddings` if that's less confusing. What do you think @dbl001 ?

**Comment by dbl001** [comment]
Sounds good!

**Comment by nateraw** [comment]
Cool! I'll be updating more stuff tonight. I'll try to get that readme updated too. I'll leave this issue open until then. Thanks guys!

**Comment by gveni** [comment]
Thanks @nateraw. For now, should I replace load_embeds and pretrained_embeddings parameters of model function with w_in = None to resolve this error?

**Comment by dbl001** [comment]
Or this:

# Load embedding matrix from file path
embedding_matrix = P.load_glove("glove.6B.300d.txt")

m = model(num_docs,
          vocab_size,
          num_topics=num_topics,
          embedding_size=embed_size,
          restore=False,
          w_in=embedding_matrix,
          freqs=freqs)

**Comment by nateraw** [comment]
@gveni what @dbl001 just commented is correct!

**Comment by gveni** [comment]
Let me download the embedding matrix and see how this goes. Thanks @dbl001 and @nateraw.

**Comment by dbl001** [comment]
FYI

**Comment by nateraw** [comment]
Links to download embeds should be in readme (but they aren't). I'll add an issue.

**Comment by gveni** [comment]
FYI, you meant 'glove.6B.50d.txt' and not 'glove.6B.300d.txt'. Otherwise it throws ValueError. Thanks

**Comment by nateraw** [comment]
Actually it depends which glove embeddings you downloaded. I have the 300 dimension ones, you must be using the 50 dimension version.

**Comment by nateraw** [comment]
When you download the glove.6B zip file, you get the 50d, 100d, 200d, and 300d versions.
