### ISSUE TITLE
run_20newsgroups.py gets OSError: File logdir_180711_0406/model.ckpt.meta does not exist

### ISSUE THREAD

**Issue by bhomass** [nateraw/Lda2vec-Tensorflow#9]
Hi I just started trying out this lib. Are the two test files load_20newsgroups.py and run_20newsgroups.py meant to run off the bat? I can get load_20newsgroups.py to run thru, but run_20newsgroups.py returns this error

OSError: File logdir_180711_0406/model.ckpt.meta does not exist.

It would be helpful if you could add a few lines, suggesting an end to end run thru. Then users can have a better direction for digging in.

**Comment by nateraw** [comment]
@bhomass delete the parameter restore or change it to False and take out the parameter "logdir". Basically I left the code the way it was when I was running a restore of a previously trained model so that I could visualize it. That should fix your problem :smile:

**Comment by bhomass** [comment]
I think you mean change restore to False. I have it running now. Thanks.
